//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttireZone_Web_App
{
    public partial class KhaltiSuccess
    {
        protected global::System.Web.UI.WebControls.Literal litTransactionId;

        protected global::System.Web.UI.WebControls.Literal litPaymentMethod;

        protected global::System.Web.UI.WebControls.PlaceHolder phEmailNotice;

        protected global::System.Web.UI.WebControls.Literal litEmailNotice;
    }
}
