//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttireZone_Web_App.Admin
{


    public partial class Dashboard
    {

        /// <summary>
        /// litUsersDelta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsersDelta;

        /// <summary>
        /// litTotalUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalUsers;

        /// <summary>
        /// litOrdersDelta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOrdersDelta;

        /// <summary>
        /// litTotalOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalOrders;

        /// <summary>
        /// litProductsDelta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProductsDelta;

        /// <summary>
        /// litTotalProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalProducts;

        /// <summary>
        /// litRevenueDelta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRevenueDelta;

        /// <summary>
        /// litTotalRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalRevenue;

        /// <summary>
        /// rptRecentOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRecentOrders;
    }
}
