//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttireZone_Web_App.Customer
{


    public partial class Cart
    {

        /// <summary>
        /// phEmptyCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEmptyCart;

        /// <summary>
        /// rptCartItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCartItems;

        /// <summary>
        /// litBagSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBagSubtotal;

        /// <summary>
        /// litSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSubtotal;

        /// <summary>
        /// litTax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTax;

        /// <summary>
        /// litGrandTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGrandTotal;

        /// <summary>
        /// btnProceedToCheckout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnProceedToCheckout;
    }
}
