//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttireZone_Web_App.Customer
{


    public partial class OrderHistory
    {

        /// <summary>
        /// btnTrackDelivery control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTrackDelivery;

        /// <summary>
        /// gvOrderHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOrderHistory;

        /// <summary>
        /// btnLoadMore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLoadMore;
    }
}
