//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttireZone_Web_App.Auth
{


    public partial class Login
    {
        protected global::System.Web.UI.WebControls.TextBox txtLoginEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLoginEmail;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revLoginEmail;

        protected global::System.Web.UI.WebControls.TextBox txtLoginPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLoginPassword;

        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
